This file is tested on python 3.11.5

In [1]:
import sdtm_generators as gs

SDTM data files generated: RS.csv, TU.csv, TR.csv

In [2]:
sdtm = gs.get_sdtm_data(6,4)

In [3]:
len(sdtm)

6

In [4]:
list(sdtm.keys())

['ae', 'cm', 'dm', 'ex', 'lb', 'vs']

In [5]:
sdtm['ae']

,PATID,AETERM,AESEV,AESTDTC,AEENDTC,AETOXGR,AEOUT,AEACT,AESER,AESDTH
0,P00001,Fever,Moderate,2023-12-08,2024-01-02,Grade 1,Improving,Drug withdrawn,Y,N
1,P00001,Nausea,Mild,2024-06-05,2024-06-14,Grade 2,Improving,Drug withdrawn,Y,Y
2,P00002,Dizziness,Moderate,2024-04-20,2024-05-09,Grade 3,Recovered,Dose not changed,Y,N
3,P00002,Fatigue,Severe,2024-05-12,2024-06-04,Grade 2,Recovered,Dose reduced,Y,Y
4,P00002,Rash,Severe,2023-10-26,2023-11-13,Grade 3,Worsened,Drug withdrawn,N,N
5,P00003,Dizziness,Mild,2024-07-12,2024-08-10,Grade 1,Improving,Drug withdrawn,Y,Y
6,P00003,Headache,Moderate,2024-02-17,2024-02-23,Grade 2,Recovered,Drug withdrawn,N,N
7,P00004,Nausea,Mild,2024-03-14,2024-04-08,Grade 2,Death,Drug withdrawn,N,Y
8,P00004,Fever,Severe,2024-07-17,2024-08-06,Grade 1,Unchanged,Dose not changed,N,Y
9,P00004,Headache,Mild,2024-03-14,2024-03-28,Grade 4,Worsened,Dose not changed,N,N
10,P00004,Fever,Mild,2024-01-10,2024-01-16,Grade 1,Unchanged,Dose reduced,N,N
11,P00004,Dizziness,Severe,2023-08-31,2023-09-08,Grade 4,Death,Dose reduced,Y,Y
12,P00004,Nausea,Moderate,2023-09-29,2023-10-25,Grade 3,Unchanged,Drug withdrawn,N,Y
13,P00005,Rash,Moderate,2023-11-21,2023-12-09,Grade 3,Unchanged,Dose reduced,Y,N
14,P00005,Rash,Moderate,2024-01-24,2024-02-01,Grade 2,Unchanged,Dose reduced,N,N
15,P00005,Fever,Severe,2024-01-01,2024-01-22,Grade 3,Improving,Dose reduced,Y,Y
16,P00006,Rash,Moderate,2023-09-24,2023-10-02,Grade 3,Death,Dose reduced,Y,N
17,P00006,Nausea,Mild,2023-12-13,2023-12-21,Grade 1,Unchanged,Drug withdrawn,N,N
18,P00006,Fever,Moderate,2024-01-12,2024-01-19,Grade 4,Death,Drug withdrawn,Y,N
19,P00006,Rash,Mild,2024-03-02,2024-03-29,Grade 2,Unchanged,Dose not changed,Y,Y

In [6]:
sdtm['cm']

    PATID        CMTRT           CMDOSFRQ CMDOSU     CMSTDTC     CMENDTC
0  P00001   Amlodipine  Three times daily     mg  2024-04-03  2024-07-29
1  P00002      Aspirin         Once daily      g  2024-04-18  2024-07-20
2  P00003  Simvastatin         Once daily     mg  2024-05-13  2024-07-16
3  P00004      Aspirin         Once daily     mg  2024-06-18  2024-07-27
4  P00005  Simvastatin        Twice daily     mg  2024-03-10  2024-07-08
5  P00006  Simvastatin         Once daily     mg  2024-07-28  2024-07-31

In [7]:
sdtm['dm']

   AGE     SEX      RACE                  ETHNIC     VISITDT   PATID
0  100    Male     White  Not Hispanic or Latino  2023-10-22  P00001
1   40    Male     White  Not Hispanic or Latino  2024-05-23  P00002
2   48  Female     Other  Not Hispanic or Latino  2024-06-30  P00003
3   20    Male     White  Not Hispanic or Latino  2024-05-03  P00004
4   57  Female  Hispanic      Hispanic or Latino  2024-03-14  P00005
5   23  Female     White      Hispanic or Latino  2023-09-27  P00006

In [8]:
sdtm['ex']

    PATID        EXTRT  EXDOSE EXDOSU     EXSTDTC     EXENDTC
0  P00001      Placebo      50     mg  2023-09-30  2024-07-14
1  P00002      Placebo      20     mg  2024-06-08  2024-07-23
2  P00003      Placebo      52     ml  2024-07-06  2024-07-17
3  P00004      Placebo      74     mg  2024-02-01  2024-07-14
4  P00005  Treatment A      27     ml  2024-06-28  2024-07-29
5  P00006      Placebo      68     mg  2024-01-28  2024-07-18

In [9]:
sdtm['lb']

      PATID       LBTEST LBSTRESU  LBSTRESN LBORRES  VISITNUM    VISIT
0    P00001   Hemoglobin     g/dL  7.678949    2.42         1  Visit 1
1    P00001  Cholesterol    mg/dL  2.171109    1.28         1  Visit 1
2    P00001      Glucose    mg/dL  0.181977    6.99         1  Visit 1
3    P00001      Calcium    mg/dL  0.558377    0.50         1  Visit 1
4    P00001    Potassium   mmol/L  6.504596    9.90         1  Visit 1
..      ...          ...      ...       ...     ...       ...      ...
115  P00006   Hemoglobin     g/dL  4.825219    5.64         4  Visit 4
116  P00006  Cholesterol    mg/dL  0.611321    4.26         4  Visit 4
117  P00006      Glucose    mg/dL  1.077206    8.66         4  Visit 4
118  P00006      Calcium    mg/dL  3.358436    6.50         4  Visit 4
119  P00006    Potassium   mmol/L  1.415713    0.81         4  Visit 4

[120 rows x 7 columns]

In [10]:
sdtm['vs']

     PATID          VSTESTCD  VSORRES     VSSTDTC    VISIT
0   P00001        Heart Rate       89  2024-07-29  Visit 1
1   P00001    Blood Pressure       71  2023-12-18  Visit 1
2   P00001  Respiratory Rate       94  2023-11-24  Visit 1
3   P00001       Temperature       80  2024-07-04  Visit 1
4   P00001        Heart Rate       90  2023-11-09  Visit 2
..     ...               ...      ...         ...      ...
91  P00006       Temperature       99  2023-10-01  Visit 3
92  P00006        Heart Rate       79  2024-04-02  Visit 4
93  P00006    Blood Pressure       86  2024-02-05  Visit 4
94  P00006  Respiratory Rate       93  2023-10-28  Visit 4
95  P00006       Temperature       90  2024-03-07  Visit 4

[96 rows x 5 columns]

In [11]:
sdtm = gs.get_sdtm_data(6,4, therapeutic_area='oncology')
list(sdtm.keys())

['ae', 'cm', 'dm', 'ex', 'lb', 'vs', 'rs', 'tu', 'tr']

In [12]:
sdtm['rs']

   USUBJID  RSSEQ       RSDTC  RSDY RSORRES             RSSTRESC
0   P00001      1  2023-08-03   214      PD  Progressive Disease
1   P00001      2  2023-04-06    95      CR    Complete Response
2   P00001      3  2023-04-15   104      SD  Progressive Disease
3   P00001      4  2023-08-12   223      SD    Complete Response
4   P00001      5  2023-09-26   268      PR    Complete Response
5   P00002      1  2023-07-13   193      PR       Stable Disease
6   P00002      2  2023-05-11   130      PR     Partial Response
7   P00002      3  2023-02-27    57      CR     Partial Response
8   P00002      4  2023-07-22   202      CR    Complete Response
9   P00002      5  2023-03-30    88      CR       Stable Disease
10  P00003      1  2023-06-13   163      SD       Stable Disease
11  P00003      2  2023-10-29   301      PD     Partial Response
12  P00003      3  2023-07-26   206      PR       Stable Disease
13  P00003      4  2023-02-06    36      PD     Partial Response
14  P00003      5  2023-02-16    46      PR       Stable Disease
15  P00004      1  2023-03-03    61      SD    Complete Response
16  P00004      2  2023-11-08   311      SD     Partial Response
17  P00004      3  2023-12-17   350      PR       Stable Disease
18  P00004      4  2023-08-17   228      PD  Progressive Disease
19  P00004      5  2023-02-21    51      PR  Progressive Disease
20  P00005      1  2023-01-20    19      CR     Partial Response
21  P00005      2  2023-07-24   204      PR     Partial Response
22  P00005      3  2023-07-11   191      PR       Stable Disease
23  P00005      4  2023-05-20   139      PD       Stable Disease
24  P00005      5  2023-04-20   109      SD       Stable Disease
25  P00006      1  2023-04-07    96      PD    Complete Response
26  P00006      2  2023-12-27   360      CR  Progressive Disease
27  P00006      3  2023-07-30   210      SD       Stable Disease
28  P00006      4  2023-07-31   211      CR     Partial Response
29  P00006      5  2023-01-18    17      CR    Complete Response

In [13]:
sdtm['tu']

   USUBJID  TUSEQ  TULOC    TUMETHOD
0   P00001      1  Brain         MRI
1   P00001      2   Lung  Ultrasound
2   P00001      3   Lung     CT Scan
3   P00001      4  Liver         MRI
4   P00001      5   Lung  Ultrasound
5   P00002      1   Bone         MRI
6   P00002      2   Bone         MRI
7   P00002      3  Liver     CT Scan
8   P00003      1   Lung  Ultrasound
9   P00003      2   Bone  Ultrasound
10  P00003      3  Liver         MRI
11  P00003      4  Brain     CT Scan
12  P00004      1   Lung     CT Scan
13  P00004      2   Lung  Ultrasound
14  P00004      3  Liver     CT Scan
15  P00004      4   Bone         MRI
16  P00004      5  Brain         MRI
17  P00005      1   Lung     CT Scan
18  P00005      2   Lung  Ultrasound
19  P00005      3  Brain     CT Scan
20  P00006      1   Bone         MRI
21  P00006      2  Brain  Ultrasound

In [14]:
sdtm['tr']

   USUBJID  TRSEQ       TRDTC  TRDY  TRLINKID   TRORRES  TRSTRESC
0   P00001      1  2023-01-11    10  TUMOR001  8.305507  8.337455
1   P00001      2  2023-11-08   311  TUMOR001  8.179829  3.320975
2   P00001      3  2023-02-24    54  TUMOR001  1.406153  2.126822
3   P00001      4  2023-04-26   115  TUMOR001  4.431903  7.688550
4   P00001      5  2023-06-16   166  TUMOR001  8.510148  1.461807
..     ...    ...         ...   ...       ...       ...       ...
60  P00006      1  2023-07-26   206  TUMOR002  7.634498  3.609891
61  P00006      2  2023-06-14   164  TUMOR002  5.088525  9.215993
62  P00006      3  2023-06-11   161  TUMOR002  4.857826  6.518421
63  P00006      4  2023-07-26   206  TUMOR002  6.082001  4.412440
64  P00006      5  2023-06-20   170  TUMOR002  3.352840  5.556363

[65 rows x 7 columns]